name: 'protected_fishing_areas'
version: '1.0.0'

profile: 'protected_fishing_areas'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  protected_fishing_areas:
    +materialized: view

    staging:
      +schema: staging
      +materialized: view

    marts:
      +schema: marts
      +materialized: table
